const SHARED_CSS = `
@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&display=swap');
*{margin:0;padding:0;box-sizing:border-box;}
body{font-family:'DM Sans',sans-serif;background:#F5F4FA;color:#1A1A2E;line-height:1.6;}
.report-container{max-width:1100px;margin:0 auto;padding:40px 24px;}
.header{background:linear-gradient(135deg,#1A1A2E 0%,#2D1554 100%);color:#fff;border-radius:16px;padding:32px;margin-bottom:24px;}
.header-logo{display:flex;align-items:center;gap:10px;margin-bottom:8px;}
.header-logo svg{width:28px;height:28px;}
.header h1{font-size:22px;font-weight:800;margin-bottom:4px;}
.header .subtitle{font-size:13px;color:#A29BFE;font-weight:500;}
.header .date-badge{display:inline-block;background:rgba(255,255,255,0.12);border-radius:8px;padding:4px 12px;font-size:12px;margin-top:10px;color:#E8E6F0;}
.exec-summary{background:#fff;border-radius:14px;padding:24px 28px;margin-bottom:20px;box-shadow:0 1px 4px rgba(0,0,0,0.04);}
.exec-summary h2{font-size:16px;font-weight:700;color:#7C3AED;margin-bottom:10px;}
.exec-summary p{font-size:14px;color:#444;line-height:1.7;}
.kpi-row{display:flex;gap:16px;margin-bottom:20px;flex-wrap:wrap;}
.kpi-card{flex:1;min-width:200px;background:#fff;border-radius:12px;padding:20px;box-shadow:0 1px 4px rgba(0,0,0,0.04);border:1px solid #EDEBF5;}
.kpi-label{font-size:12px;font-weight:600;color:#888;text-transform:uppercase;letter-spacing:0.4px;margin-bottom:6px;}
.kpi-value{font-size:28px;font-weight:800;color:#1A1A2E;line-height:1.2;}
.kpi-delta{font-size:13px;font-weight:600;margin-top:4px;}
.kpi-delta.positive{color:#00B894;}
.kpi-delta.negative{color:#E74C3C;}
.chart-section{background:#fff;border-radius:14px;padding:28px;margin-top:20px;box-shadow:0 1px 4px rgba(0,0,0,0.04);}
.chart-section h3{font-size:15px;font-weight:700;color:#1A1A2E;margin-bottom:16px;}
.table-section{background:#fff;border-radius:14px;padding:28px;margin-top:20px;box-shadow:0 1px 4px rgba(0,0,0,0.04);}
.table-section h3{font-size:15px;font-weight:700;color:#1A1A2E;margin-bottom:16px;}
.data-table{width:100%;border-collapse:collapse;font-size:13px;}
.data-table th{background:#F0EDFF;color:#6C5CE7;padding:12px 10px;text-align:left;font-weight:700;font-size:12px;text-transform:uppercase;letter-spacing:0.3px;}
.data-table td{padding:10px;border-bottom:1px solid #E8E6F0;color:#333;}
.data-table tr:nth-child(even){background:#FAFAFF;}
.data-table tr:hover{background:#F0EDFF;}
.tag{display:inline-block;padding:2px 8px;border-radius:6px;font-size:11px;font-weight:600;}
.tag-high{background:#FFEAEA;color:#E74C3C;}
.tag-medium{background:#FFF4E0;color:#E17055;}
.tag-low{background:#E8FFF0;color:#00B894;}
.recommendations{background:#F0FFF4;border-radius:14px;padding:24px 28px;margin-top:20px;border:1px solid #C6F6D5;}
.recommendations h3{font-size:15px;font-weight:700;color:#00B894;margin-bottom:12px;}
.recommendations ul{list-style:none;padding:0;}
.recommendations li{padding:8px 0;font-size:14px;color:#333;border-bottom:1px solid #E2F5EA;display:flex;align-items:flex-start;gap:8px;}
.recommendations li:last-child{border-bottom:none;}
.recommendations li::before{content:"\\2713";color:#00B894;font-weight:700;flex-shrink:0;}
.footer{text-align:center;color:#999;padding:24px 0;font-size:12px;}
`;

const CANVAS_REPORTS = {

// ══════════════════════════════════════════════════════════════════════
// t1 — Out-of-Stock Impact Trends Report
// ══════════════════════════════════════════════════════════════════════
t1: `<!DOCTYPE html><html><head><style>${SHARED_CSS}</style></head><body>
<div class="report-container">

<div class="header">
  <div class="header-logo">
    <svg viewBox="0 0 28 28" fill="none"><rect width="28" height="28" rx="8" fill="#7C3AED"/><path d="M7 14h4l3-6 4 12 3-6h4" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
    <span style="font-size:16px;font-weight:700;">HarmonIQ</span>
  </div>
  <h1>Out-of-Stock Impact Trends Report &mdash; Week 6, 2026</h1>
  <div class="subtitle">Generated by HarmonIQ &nbsp;|&nbsp; IngestIQ + VisionIQ + DemandIQ + OptimaIQ</div>
  <div class="date-badge">Report Period: Feb 3 &ndash; Feb 9, 2026 &nbsp;&bull;&nbsp; Generated: Feb 10, 2026 08:12 AM</div>
</div>

<div class="exec-summary">
  <h2>Executive Summary</h2>
  <p>During Week 6, <strong>847 out-of-stock incidents</strong> were recorded across the monitored estate, contributing to an estimated <strong>&pound;4.2M in lost revenue</strong>. The top 15 SKUs accounted for 63% of total loss, with Spirits and RTD categories driving the majority of impact. Targeted replenishment interventions reduced lost revenue by 8% compared to the prior period. Recovery rate improved to 67%, up 23 percentage points following automated safety-stock adjustments deployed in Week 4.</p>
</div>

<div class="kpi-row">
  <div class="kpi-card"><div class="kpi-label">OOS Incidents</div><div class="kpi-value">847</div><div class="kpi-delta negative">&uarr; +12% vs prior week</div></div>
  <div class="kpi-card"><div class="kpi-label">Lost Revenue</div><div class="kpi-value">&pound;4.2M</div><div class="kpi-delta positive">&darr; -8% with intervention</div></div>
  <div class="kpi-card"><div class="kpi-label">Recovery Rate</div><div class="kpi-value">67%</div><div class="kpi-delta positive">&uarr; +23pp vs baseline</div></div>
  <div class="kpi-card"><div class="kpi-label">Priority SKUs</div><div class="kpi-value">15</div><div class="kpi-delta negative">Top 3.1% of portfolio</div></div>
</div>

<div class="chart-section">
  <h3>OOS Incidents by Category</h3>
  <svg viewBox="0 0 600 280" width="100%" style="display:block;">
    <line x1="60" y1="30" x2="60" y2="230" stroke="#E8E6F0" stroke-width="1"/>
    <line x1="60" y1="230" x2="580" y2="230" stroke="#E8E6F0" stroke-width="1"/>
    <line x1="60" y1="180" x2="580" y2="180" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <line x1="60" y1="130" x2="580" y2="130" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <line x1="60" y1="80" x2="580" y2="80" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <text x="55" y="234" text-anchor="end" font-size="11" fill="#999" font-family="DM Sans">0</text>
    <text x="55" y="184" text-anchor="end" font-size="11" fill="#999" font-family="DM Sans">100</text>
    <text x="55" y="134" text-anchor="end" font-size="11" fill="#999" font-family="DM Sans">200</text>
    <text x="55" y="84" text-anchor="end" font-size="11" fill="#999" font-family="DM Sans">300</text>
    <rect x="90" y="38" width="70" height="192" rx="3" fill="#7C3AED"/>
    <text x="125" y="32" text-anchor="middle" font-size="12" font-weight="700" fill="#7C3AED" font-family="DM Sans">312</text>
    <text x="125" y="250" text-anchor="middle" font-size="11" fill="#666" font-family="DM Sans">Spirits</text>
    <rect x="190" y="96" width="70" height="134" rx="3" fill="#A29BFE"/>
    <text x="225" y="90" text-anchor="middle" font-size="12" font-weight="700" fill="#A29BFE" font-family="DM Sans">218</text>
    <text x="225" y="250" text-anchor="middle" font-size="11" fill="#666" font-family="DM Sans">RTD</text>
    <rect x="290" y="115" width="70" height="115" rx="3" fill="#7C3AED"/>
    <text x="325" y="109" text-anchor="middle" font-size="12" font-weight="700" fill="#7C3AED" font-family="DM Sans">187</text>
    <text x="325" y="250" text-anchor="middle" font-size="11" fill="#666" font-family="DM Sans">Beer</text>
    <rect x="390" y="180" width="70" height="50" rx="3" fill="#A29BFE"/>
    <text x="425" y="174" text-anchor="middle" font-size="12" font-weight="700" fill="#A29BFE" font-family="DM Sans">82</text>
    <text x="425" y="250" text-anchor="middle" font-size="11" fill="#666" font-family="DM Sans">Wine</text>
    <rect x="490" y="201" width="70" height="29" rx="3" fill="#7C3AED"/>
    <text x="525" y="195" text-anchor="middle" font-size="12" font-weight="700" fill="#7C3AED" font-family="DM Sans">48</text>
    <text x="525" y="250" text-anchor="middle" font-size="11" fill="#666" font-family="DM Sans">Liqueur</text>
  </svg>
</div>

<div class="chart-section">
  <h3>Weekly OOS Trend (12 Weeks) &mdash; with Intervention Point</h3>
  <svg viewBox="0 0 600 260" width="100%" style="display:block;">
    <line x1="50" y1="20" x2="50" y2="210" stroke="#E8E6F0" stroke-width="1"/>
    <line x1="50" y1="210" x2="580" y2="210" stroke="#E8E6F0" stroke-width="1"/>
    <line x1="50" y1="160" x2="580" y2="160" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <line x1="50" y1="110" x2="580" y2="110" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <line x1="50" y1="60" x2="580" y2="60" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <text x="45" y="214" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">40</text>
    <text x="45" y="164" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">60</text>
    <text x="45" y="114" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">80</text>
    <text x="45" y="64" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">100</text>
    <polyline points="70,42 115,54 160,50 205,68 250,85 295,78 340,100 385,120 430,138 475,155 520,168 565,172" fill="none" stroke="#7C3AED" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
    <line x1="250" y1="20" x2="250" y2="210" stroke="#E74C3C" stroke-width="1.5" stroke-dasharray="6,3"/>
    <text x="254" y="34" font-size="10" fill="#E74C3C" font-family="DM Sans" font-weight="600">Intervention (Wk4)</text>
    <circle cx="70" cy="42" r="4" fill="#7C3AED"/><circle cx="115" cy="54" r="4" fill="#7C3AED"/>
    <circle cx="160" cy="50" r="4" fill="#7C3AED"/><circle cx="205" cy="68" r="4" fill="#7C3AED"/>
    <circle cx="250" cy="85" r="4" fill="#E74C3C"/><circle cx="295" cy="78" r="4" fill="#7C3AED"/>
    <circle cx="340" cy="100" r="4" fill="#7C3AED"/><circle cx="385" cy="120" r="4" fill="#7C3AED"/>
    <circle cx="430" cy="138" r="4" fill="#00B894"/><circle cx="475" cy="155" r="4" fill="#00B894"/>
    <circle cx="520" cy="168" r="4" fill="#00B894"/><circle cx="565" cy="172" r="4" fill="#00B894"/>
    <text x="70" y="237" text-anchor="middle" font-size="9" fill="#999" font-family="DM Sans">W1</text>
    <text x="160" y="237" text-anchor="middle" font-size="9" fill="#999" font-family="DM Sans">W3</text>
    <text x="250" y="237" text-anchor="middle" font-size="9" fill="#999" font-family="DM Sans">W5</text>
    <text x="340" y="237" text-anchor="middle" font-size="9" fill="#999" font-family="DM Sans">W7</text>
    <text x="430" y="237" text-anchor="middle" font-size="9" fill="#999" font-family="DM Sans">W9</text>
    <text x="565" y="237" text-anchor="middle" font-size="9" fill="#999" font-family="DM Sans">W12</text>
  </svg>
</div>

<div class="table-section">
  <h3>Priority SKU Detail &mdash; Top 10 by Lost Revenue</h3>
  <div style="overflow-x:auto;">
  <table class="data-table">
    <thead><tr><th>SKU</th><th>Product</th><th>Category</th><th>OOS Wks</th><th>Lost Units</th><th>Lost Rev (&pound;)</th><th>Priority</th></tr></thead>
    <tbody>
      <tr><td>DG-1042</td><td>Johnnie Walker Black 70cl</td><td>Spirits</td><td>4</td><td>12,840</td><td>&pound;384,200</td><td><span class="tag tag-high">Critical</span></td></tr>
      <tr><td>DG-2087</td><td>Tanqueray London Dry 70cl</td><td>Spirits</td><td>3</td><td>9,620</td><td>&pound;312,650</td><td><span class="tag tag-high">Critical</span></td></tr>
      <tr><td>DG-3511</td><td>Smirnoff Ice Original 4pk</td><td>RTD</td><td>5</td><td>18,200</td><td>&pound;291,200</td><td><span class="tag tag-high">Critical</span></td></tr>
      <tr><td>DG-1198</td><td>Bulleit Bourbon 70cl</td><td>Spirits</td><td>3</td><td>7,340</td><td>&pound;256,900</td><td><span class="tag tag-high">Critical</span></td></tr>
      <tr><td>DG-4420</td><td>Guinness Draught 4pk</td><td>Beer</td><td>4</td><td>22,100</td><td>&pound;243,100</td><td><span class="tag tag-high">Critical</span></td></tr>
      <tr><td>DG-2201</td><td>Gordon&rsquo;s Pink Gin 70cl</td><td>Spirits</td><td>2</td><td>6,480</td><td>&pound;194,400</td><td><span class="tag tag-medium">High</span></td></tr>
      <tr><td>DG-3088</td><td>Captain Morgan Spiced 1L</td><td>Spirits</td><td>3</td><td>5,920</td><td>&pound;177,600</td><td><span class="tag tag-medium">High</span></td></tr>
      <tr><td>DG-5530</td><td>Hop House 13 Lager 12pk</td><td>Beer</td><td>2</td><td>8,400</td><td>&pound;168,000</td><td><span class="tag tag-medium">High</span></td></tr>
      <tr><td>DG-3901</td><td>Gordon&rsquo;s Sicilian Lemon RTD 4pk</td><td>RTD</td><td>4</td><td>10,250</td><td>&pound;153,750</td><td><span class="tag tag-medium">High</span></td></tr>
      <tr><td>DG-6612</td><td>Baileys Original 70cl</td><td>Liqueur</td><td>2</td><td>4,800</td><td>&pound;144,000</td><td><span class="tag tag-low">Monitor</span></td></tr>
    </tbody>
  </table>
  </div>
</div>

<div class="recommendations">
  <h3>Recommendations</h3>
  <ul>
    <li>Increase safety stock by 20% for the 15 critical SKUs, prioritising Johnnie Walker Black and Tanqueray London Dry, which together represent &pound;697K in lost revenue.</li>
    <li>Implement automated replenishment triggers for RTD category at the depot level; current lead-time of 72 hours is exceeding OOS tolerance for fast-moving SKUs.</li>
    <li>Negotiate expedited delivery windows with the Spirits distribution hub for weeks identified by DemandIQ as high-demand (Weeks 8, 12, 16).</li>
    <li>Deploy shelf-sensor monitoring in the 12 highest-impact stores to enable real-time OOS detection and reduce mean time-to-replenish from 48 to 18 hours.</li>
  </ul>
</div>

<div class="footer">HarmonIQ &mdash; Intelligent Analytics Platform &nbsp;&bull;&nbsp; Confidential &nbsp;&bull;&nbsp; &copy; 2026 Aria Intelligence Systems</div>

</div>
</body></html>`,

// ══════════════════════════════════════════════════════════════════════
// t2 — Sales Gap Optimization
// ══════════════════════════════════════════════════════════════════════
t2: `<!DOCTYPE html><html><head><style>${SHARED_CSS}</style></head><body>
<div class="report-container">

<div class="header">
  <div class="header-logo">
    <svg viewBox="0 0 28 28" fill="none"><rect width="28" height="28" rx="8" fill="#7C3AED"/><path d="M7 14h4l3-6 4 12 3-6h4" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
    <span style="font-size:16px;font-weight:700;">HarmonIQ</span>
  </div>
  <h1>Sales Gap Analysis &amp; Pricing Strategy &mdash; FY2026</h1>
  <div class="subtitle">Generated by HarmonIQ &nbsp;|&nbsp; IngestIQ + MarketIQ + DemandIQ + OptimaIQ</div>
  <div class="date-badge">Fiscal Year 2026 YTD (Apr 2025 &ndash; Jan 2026) &nbsp;&bull;&nbsp; Generated: Feb 11, 2026 14:30 PM</div>
</div>

<div class="exec-summary">
  <h2>Executive Summary</h2>
  <p>Year-to-date volume stands at <strong>672K units</strong> against a full-year target of 724K, leaving a <strong>52K unit gap (7.2%)</strong>. Targeted pricing interventions and channel-specific promotions have already recovered 40.5K units (78% of recoverable gap). Blended margin has been preserved at 14.3%, only 0.7pp below plan. Three brands remain at risk of missing annual targets, down from five at the start of Q3.</p>
</div>

<div class="kpi-row">
  <div class="kpi-card"><div class="kpi-label">Volume Gap</div><div class="kpi-value">52K units</div><div class="kpi-delta negative">&darr; -7.2% vs target</div></div>
  <div class="kpi-card"><div class="kpi-label">Gap Recovery</div><div class="kpi-value">78%</div><div class="kpi-delta positive">&uarr; +40.5K recovered</div></div>
  <div class="kpi-card"><div class="kpi-label">Margin Preserved</div><div class="kpi-value">14.3%</div><div class="kpi-delta negative">&darr; -0.7pp vs plan</div></div>
  <div class="kpi-card"><div class="kpi-label">Brands at Risk</div><div class="kpi-value">3 / 8</div><div class="kpi-delta positive">&darr; Down from 5</div></div>
</div>

<div class="chart-section">
  <h3>YTD Actual vs Target by Brand (Units, 000s)</h3>
  <svg viewBox="0 0 620 300" width="100%" style="display:block;">
    <line x1="60" y1="20" x2="60" y2="240" stroke="#E8E6F0" stroke-width="1"/>
    <line x1="60" y1="240" x2="600" y2="240" stroke="#E8E6F0" stroke-width="1"/>
    <line x1="60" y1="190" x2="600" y2="190" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <line x1="60" y1="140" x2="600" y2="140" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <line x1="60" y1="90" x2="600" y2="90" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <line x1="60" y1="40" x2="600" y2="40" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <text x="55" y="244" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">0</text>
    <text x="55" y="194" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">50</text>
    <text x="55" y="144" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">100</text>
    <text x="55" y="94" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">150</text>
    <text x="55" y="44" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">200</text>
    <!-- JW -->
    <rect x="78" y="52" width="30" height="188" rx="3" fill="#7C3AED"/>
    <rect x="112" y="40" width="30" height="200" rx="3" fill="#A29BFE"/>
    <text x="110" y="270" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">J. Walker</text>
    <!-- Tanqueray -->
    <rect x="168" y="100" width="30" height="140" rx="3" fill="#7C3AED"/>
    <rect x="202" y="90" width="30" height="150" rx="3" fill="#A29BFE"/>
    <text x="200" y="270" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">Tanqueray</text>
    <!-- Smirnoff -->
    <rect x="258" y="72" width="30" height="168" rx="3" fill="#7C3AED"/>
    <rect x="292" y="60" width="30" height="180" rx="3" fill="#A29BFE"/>
    <text x="290" y="270" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">Smirnoff</text>
    <!-- Guinness -->
    <rect x="348" y="112" width="30" height="128" rx="3" fill="#7C3AED"/>
    <rect x="382" y="108" width="30" height="132" rx="3" fill="#A29BFE"/>
    <text x="380" y="270" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">Guinness</text>
    <!-- Baileys -->
    <rect x="438" y="160" width="30" height="80" rx="3" fill="#7C3AED"/>
    <rect x="472" y="140" width="30" height="100" rx="3" fill="#A29BFE"/>
    <text x="470" y="270" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">Baileys</text>
    <!-- Captain Morgan -->
    <rect x="528" y="148" width="30" height="92" rx="3" fill="#7C3AED"/>
    <rect x="562" y="140" width="30" height="100" rx="3" fill="#A29BFE"/>
    <text x="560" y="270" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">Capt. Morgan</text>
    <!-- Legend -->
    <rect x="80" y="288" width="12" height="8" rx="2" fill="#7C3AED"/><text x="96" y="296" font-size="10" fill="#666" font-family="DM Sans">Actual</text>
    <rect x="150" y="288" width="12" height="8" rx="2" fill="#A29BFE"/><text x="166" y="296" font-size="10" fill="#666" font-family="DM Sans">Target</text>
  </svg>
</div>

<div class="chart-section">
  <h3>Gap Decomposition Waterfall (Units, 000s)</h3>
  <svg viewBox="0 0 600 220" width="100%" style="display:block;">
    <line x1="50" y1="180" x2="570" y2="180" stroke="#E8E6F0" stroke-width="1"/>
    <!-- Target bar -->
    <rect x="70" y="40" width="60" height="140" rx="3" fill="#A29BFE"/>
    <text x="100" y="34" text-anchor="middle" font-size="11" font-weight="700" fill="#A29BFE" font-family="DM Sans">724K</text>
    <text x="100" y="198" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">Target</text>
    <!-- Price gap (negative) -->
    <rect x="160" y="40" width="60" height="48" rx="3" fill="#E74C3C"/>
    <text x="190" y="34" text-anchor="middle" font-size="11" font-weight="700" fill="#E74C3C" font-family="DM Sans">-28K</text>
    <text x="190" y="198" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">Price Gap</text>
    <!-- Distribution gap -->
    <rect x="250" y="88" width="60" height="32" rx="3" fill="#E74C3C"/>
    <text x="280" y="82" text-anchor="middle" font-size="11" font-weight="700" fill="#E74C3C" font-family="DM Sans">-18K</text>
    <text x="280" y="198" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">Distrib. Gap</text>
    <!-- OOS gap -->
    <rect x="340" y="120" width="60" height="16" rx="3" fill="#E74C3C"/>
    <text x="370" y="114" text-anchor="middle" font-size="11" font-weight="700" fill="#E74C3C" font-family="DM Sans">-6K</text>
    <text x="370" y="198" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">OOS Gap</text>
    <!-- Recovered -->
    <rect x="430" y="92" width="60" height="44" rx="3" fill="#00B894"/>
    <text x="460" y="86" text-anchor="middle" font-size="11" font-weight="700" fill="#00B894" font-family="DM Sans">+40.5K</text>
    <text x="460" y="198" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">Recovered</text>
    <!-- Actual -->
    <rect x="520" y="58" width="60" height="122" rx="3" fill="#7C3AED"/>
    <text x="550" y="52" text-anchor="middle" font-size="11" font-weight="700" fill="#7C3AED" font-family="DM Sans">672K</text>
    <text x="550" y="198" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">Actual YTD</text>
  </svg>
</div>

<div class="table-section">
  <h3>Brand &times; Channel Gap Analysis</h3>
  <div style="overflow-x:auto;">
  <table class="data-table">
    <thead><tr><th>Brand</th><th>Channel</th><th>YTD Actual</th><th>Target</th><th>Gap</th><th>Rec. Discount</th><th>Proj. Recovery</th></tr></thead>
    <tbody>
      <tr><td>Johnnie Walker</td><td>On-Trade</td><td>94,200</td><td>100,000</td><td style="color:#E74C3C;">-5,800</td><td>4.5%</td><td>4,200</td></tr>
      <tr><td>Johnnie Walker</td><td>Off-Trade</td><td>93,800</td><td>100,000</td><td style="color:#E74C3C;">-6,200</td><td>3.2%</td><td>5,100</td></tr>
      <tr><td>Tanqueray</td><td>On-Trade</td><td>68,400</td><td>75,000</td><td style="color:#E74C3C;">-6,600</td><td>5.0%</td><td>5,800</td></tr>
      <tr><td>Smirnoff</td><td>Off-Trade</td><td>84,000</td><td>90,000</td><td style="color:#E74C3C;">-6,000</td><td>6.0%</td><td>5,500</td></tr>
      <tr><td>Guinness</td><td>On-Trade</td><td>64,200</td><td>66,000</td><td style="color:#E74C3C;">-1,800</td><td>2.0%</td><td>1,600</td></tr>
      <tr><td>Baileys</td><td>Off-Trade</td><td>38,500</td><td>50,000</td><td style="color:#E74C3C;">-11,500</td><td>8.0%</td><td>8,200</td></tr>
      <tr><td>Captain Morgan</td><td>Off-Trade</td><td>46,000</td><td>50,000</td><td style="color:#E74C3C;">-4,000</td><td>4.0%</td><td>3,400</td></tr>
      <tr><td>Captain Morgan</td><td>On-Trade</td><td>46,000</td><td>50,000</td><td style="color:#E74C3C;">-4,000</td><td>3.5%</td><td>3,200</td></tr>
    </tbody>
  </table>
  </div>
</div>

<div class="recommendations">
  <h3>Recommendations</h3>
  <ul>
    <li>Deploy targeted promotional pricing for Baileys Off-Trade (8% discount) during Feb&ndash;Mar to close the &pound;11.5K unit gap; OptimaIQ projects 71% recovery at 12.8% margin.</li>
    <li>Shift &pound;120K of trade spend from Guinness On-Trade (near target) to Tanqueray On-Trade where elasticity modelling shows 1.4x higher lift per &pound; spent.</li>
    <li>Negotiate expanded distribution for Captain Morgan in 240 independent off-licences currently stocking only Smirnoff and Johnnie Walker.</li>
    <li>Introduce a Smirnoff &amp; Captain Morgan cross-brand bundle offer for the Off-Trade impulse channel, projected to deliver an incremental 3,800 units at 15.1% margin.</li>
  </ul>
</div>

<div class="footer">HarmonIQ &mdash; Intelligent Analytics Platform &nbsp;&bull;&nbsp; Confidential &nbsp;&bull;&nbsp; &copy; 2026 Aria Intelligence Systems</div>

</div>
</body></html>`,

// ══════════════════════════════════════════════════════════════════════
// t3 — Competitor Price Monitor
// ══════════════════════════════════════════════════════════════════════
t3: `<!DOCTYPE html><html><head><style>${SHARED_CSS}</style></head><body>
<div class="report-container">

<div class="header">
  <div class="header-logo">
    <svg viewBox="0 0 28 28" fill="none"><rect width="28" height="28" rx="8" fill="#7C3AED"/><path d="M7 14h4l3-6 4 12 3-6h4" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
    <span style="font-size:16px;font-weight:700;">HarmonIQ</span>
  </div>
  <h1>Competitive Price Intelligence Report &mdash; Q1 2026</h1>
  <div class="subtitle">Generated by HarmonIQ &nbsp;|&nbsp; IngestIQ + VisionIQ+ + MarketIQ + OptimaIQ</div>
  <div class="date-badge">Period: Jan 1 &ndash; Feb 9, 2026 &nbsp;&bull;&nbsp; Generated: Feb 10, 2026 10:45 AM</div>
</div>

<div class="exec-summary">
  <h2>Executive Summary</h2>
  <p>Our portfolio&rsquo;s average price index stands at <strong>103.2</strong> (vs category median = 100), indicating a slight premium positioning. Of 3,220 monitored SKUs, <strong>184 (5.7%) are priced above the competitive median</strong> by more than 5%. Eight SKUs show high price-elasticity alerts (|&epsilon;| &gt; 1.8), with an estimated <strong>&pound;1.6M revenue at risk</strong> from competitive undercutting. Immediate action is recommended on 3 Spirits SKUs where competitors have dropped shelf price by &gt;8%.</p>
</div>

<div class="kpi-row">
  <div class="kpi-card"><div class="kpi-label">Avg Price Index</div><div class="kpi-value">103.2</div><div class="kpi-delta negative">&uarr; +3.2% vs median</div></div>
  <div class="kpi-card"><div class="kpi-label">SKUs Above Median</div><div class="kpi-value">184</div><div class="kpi-delta negative">5.7% of portfolio</div></div>
  <div class="kpi-card"><div class="kpi-label">Elasticity Alerts</div><div class="kpi-value">8</div><div class="kpi-delta negative">|&epsilon;| &gt; 1.8</div></div>
  <div class="kpi-card"><div class="kpi-label">Revenue at Risk</div><div class="kpi-value">&pound;1.6M</div><div class="kpi-delta positive">&darr; -0.4pp vs Q4</div></div>
</div>

<div class="chart-section">
  <h3>Price Comparison &mdash; Top 8 SKUs (&pound;)</h3>
  <svg viewBox="0 0 620 320" width="100%" style="display:block;">
    <line x1="60" y1="20" x2="60" y2="250" stroke="#E8E6F0" stroke-width="1"/>
    <line x1="60" y1="250" x2="600" y2="250" stroke="#E8E6F0" stroke-width="1"/>
    <line x1="60" y1="200" x2="600" y2="200" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <line x1="60" y1="150" x2="600" y2="150" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <line x1="60" y1="100" x2="600" y2="100" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <line x1="60" y1="50" x2="600" y2="50" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <text x="55" y="254" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">&pound;0</text>
    <text x="55" y="204" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">&pound;10</text>
    <text x="55" y="154" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">&pound;20</text>
    <text x="55" y="104" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">&pound;30</text>
    <text x="55" y="54" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">&pound;40</text>
    <!-- SKU 1: JW Black -->
    <rect x="75" y="100" width="16" height="150" rx="2" fill="#7C3AED"/>
    <rect x="93" y="115" width="16" height="135" rx="2" fill="#A29BFE"/>
    <rect x="111" y="110" width="16" height="140" rx="2" fill="#00B894"/>
    <text x="100" y="270" text-anchor="middle" font-size="8" fill="#666" font-family="DM Sans">JW Black</text>
    <!-- SKU 2: Tanqueray -->
    <rect x="145" y="120" width="16" height="130" rx="2" fill="#7C3AED"/>
    <rect x="163" y="130" width="16" height="120" rx="2" fill="#A29BFE"/>
    <rect x="181" y="125" width="16" height="125" rx="2" fill="#00B894"/>
    <text x="170" y="270" text-anchor="middle" font-size="8" fill="#666" font-family="DM Sans">Tanqueray</text>
    <!-- SKU 3: Smirnoff -->
    <rect x="215" y="175" width="16" height="75" rx="2" fill="#7C3AED"/>
    <rect x="233" y="180" width="16" height="70" rx="2" fill="#A29BFE"/>
    <rect x="251" y="170" width="16" height="80" rx="2" fill="#00B894"/>
    <text x="240" y="270" text-anchor="middle" font-size="8" fill="#666" font-family="DM Sans">Smirnoff</text>
    <!-- SKU 4: Bulleit -->
    <rect x="285" y="105" width="16" height="145" rx="2" fill="#7C3AED"/>
    <rect x="303" y="120" width="16" height="130" rx="2" fill="#A29BFE"/>
    <rect x="321" y="118" width="16" height="132" rx="2" fill="#00B894"/>
    <text x="310" y="270" text-anchor="middle" font-size="8" fill="#666" font-family="DM Sans">Bulleit</text>
    <!-- SKU 5: Gordon's -->
    <rect x="355" y="155" width="16" height="95" rx="2" fill="#7C3AED"/>
    <rect x="373" y="160" width="16" height="90" rx="2" fill="#A29BFE"/>
    <rect x="391" y="148" width="16" height="102" rx="2" fill="#00B894"/>
    <text x="380" y="270" text-anchor="middle" font-size="8" fill="#666" font-family="DM Sans">Gordon's</text>
    <!-- SKU 6: Capt Morgan -->
    <rect x="425" y="140" width="16" height="110" rx="2" fill="#7C3AED"/>
    <rect x="443" y="150" width="16" height="100" rx="2" fill="#A29BFE"/>
    <rect x="461" y="145" width="16" height="105" rx="2" fill="#00B894"/>
    <text x="450" y="270" text-anchor="middle" font-size="8" fill="#666" font-family="DM Sans">Capt Morgan</text>
    <!-- SKU 7: Guinness -->
    <rect x="495" y="190" width="16" height="60" rx="2" fill="#7C3AED"/>
    <rect x="513" y="195" width="16" height="55" rx="2" fill="#A29BFE"/>
    <rect x="531" y="192" width="16" height="58" rx="2" fill="#00B894"/>
    <text x="520" y="270" text-anchor="middle" font-size="8" fill="#666" font-family="DM Sans">Guinness</text>
    <!-- SKU 8: Baileys -->
    <rect x="558" y="155" width="16" height="95" rx="2" fill="#7C3AED"/>
    <rect x="576" y="148" width="16" height="102" rx="2" fill="#A29BFE"/>
    <text x="575" y="270" text-anchor="middle" font-size="8" fill="#666" font-family="DM Sans">Baileys</text>
    <!-- Legend -->
    <rect x="80" y="290" width="12" height="8" rx="2" fill="#7C3AED"/><text x="96" y="298" font-size="10" fill="#666" font-family="DM Sans">Our Price</text>
    <rect x="170" y="290" width="12" height="8" rx="2" fill="#A29BFE"/><text x="186" y="298" font-size="10" fill="#666" font-family="DM Sans">Comp A</text>
    <rect x="250" y="290" width="12" height="8" rx="2" fill="#00B894"/><text x="266" y="298" font-size="10" fill="#666" font-family="DM Sans">Comp B</text>
  </svg>
</div>

<div class="chart-section">
  <h3>Price Index Distribution (SKU Count by Range)</h3>
  <svg viewBox="0 0 600 200" width="100%" style="display:block;">
    <text x="90" y="30" font-size="11" fill="#666" font-family="DM Sans">&lt;95</text>
    <rect x="130" y="18" width="120" height="22" rx="3" fill="#00B894"/><text x="258" y="34" font-size="11" fill="#333" font-family="DM Sans" font-weight="600">312</text>
    <text x="90" y="66" font-size="11" fill="#666" font-family="DM Sans">95&ndash;100</text>
    <rect x="130" y="54" width="340" height="22" rx="3" fill="#7C3AED"/><text x="478" y="70" font-size="11" fill="#333" font-family="DM Sans" font-weight="600">892</text>
    <text x="90" y="102" font-size="11" fill="#666" font-family="DM Sans">100&ndash;105</text>
    <rect x="130" y="90" width="420" height="22" rx="3" fill="#A29BFE"/><text x="558" y="106" font-size="11" fill="#333" font-family="DM Sans" font-weight="600">1,104</text>
    <text x="90" y="138" font-size="11" fill="#666" font-family="DM Sans">105&ndash;110</text>
    <rect x="130" y="126" width="260" height="22" rx="3" fill="#E17055"/><text x="398" y="142" font-size="11" fill="#333" font-family="DM Sans" font-weight="600">680</text>
    <text x="90" y="174" font-size="11" fill="#666" font-family="DM Sans">&gt;110</text>
    <rect x="130" y="162" width="88" height="22" rx="3" fill="#E74C3C"/><text x="226" y="178" font-size="11" fill="#333" font-family="DM Sans" font-weight="600">232</text>
  </svg>
</div>

<div class="table-section">
  <h3>Competitive Price Detail &mdash; Top 10 SKUs</h3>
  <div style="overflow-x:auto;">
  <table class="data-table">
    <thead><tr><th>SKU</th><th>Product</th><th>Our Price</th><th>Comp A</th><th>Comp B</th><th>Index</th><th>Elasticity</th><th>Action</th></tr></thead>
    <tbody>
      <tr><td>DG-1042</td><td>JW Black Label 70cl</td><td>&pound;30.00</td><td>&pound;27.50</td><td>&pound;28.00</td><td>108.1</td><td>-2.1</td><td><span class="tag tag-high">Reprice</span></td></tr>
      <tr><td>DG-2087</td><td>Tanqueray 70cl</td><td>&pound;26.00</td><td>&pound;24.00</td><td>&pound;25.00</td><td>106.1</td><td>-1.9</td><td><span class="tag tag-high">Reprice</span></td></tr>
      <tr><td>DG-1198</td><td>Bulleit Bourbon 70cl</td><td>&pound;29.00</td><td>&pound;26.00</td><td>&pound;26.50</td><td>110.5</td><td>-2.3</td><td><span class="tag tag-high">Reprice</span></td></tr>
      <tr><td>DG-3088</td><td>Captain Morgan Spiced 1L</td><td>&pound;22.00</td><td>&pound;20.00</td><td>&pound;21.00</td><td>107.3</td><td>-1.8</td><td><span class="tag tag-medium">Monitor</span></td></tr>
      <tr><td>DG-2201</td><td>Gordon&rsquo;s Pink Gin 70cl</td><td>&pound;19.00</td><td>&pound;18.00</td><td>&pound;20.50</td><td>98.7</td><td>-1.4</td><td><span class="tag tag-low">Hold</span></td></tr>
      <tr><td>DG-3511</td><td>Smirnoff Ice 4pk</td><td>&pound;5.50</td><td>&pound;5.00</td><td>&pound;5.25</td><td>107.3</td><td>-1.6</td><td><span class="tag tag-medium">Monitor</span></td></tr>
      <tr><td>DG-4420</td><td>Guinness Draught 4pk</td><td>&pound;6.80</td><td>&pound;6.50</td><td>&pound;6.70</td><td>103.0</td><td>-1.2</td><td><span class="tag tag-low">Hold</span></td></tr>
      <tr><td>DG-6612</td><td>Baileys Original 70cl</td><td>&pound;19.00</td><td>&pound;20.50</td><td>&pound;18.50</td><td>97.9</td><td>-1.1</td><td><span class="tag tag-low">Hold</span></td></tr>
      <tr><td>DG-7745</td><td>Singleton 12yr 70cl</td><td>&pound;34.00</td><td>&pound;31.00</td><td>&pound;32.00</td><td>108.3</td><td>-1.9</td><td><span class="tag tag-high">Reprice</span></td></tr>
      <tr><td>DG-8832</td><td>Ciroc Vodka 70cl</td><td>&pound;38.00</td><td>&pound;36.50</td><td>&pound;37.00</td><td>103.4</td><td>-1.5</td><td><span class="tag tag-medium">Monitor</span></td></tr>
    </tbody>
  </table>
  </div>
</div>

<div class="recommendations">
  <h3>Recommendations</h3>
  <ul>
    <li>Immediately reprice JW Black Label, Tanqueray, and Bulleit Bourbon in Off-Trade to close the &gt;8% gap vs Competitor A; projected to recover &pound;640K in at-risk revenue.</li>
    <li>Maintain premium positioning on Baileys and Guinness where price index is near/below 100 and elasticity is low (&lt;1.4).</li>
    <li>Launch a temporary &ldquo;price match&rdquo; campaign on Captain Morgan 1L in high-competition postcodes identified by MarketIQ geo-analysis.</li>
    <li>Set up automated weekly price alerts for the 8 high-elasticity SKUs to enable faster response when competitors adjust shelf prices.</li>
  </ul>
</div>

<div class="footer">HarmonIQ &mdash; Intelligent Analytics Platform &nbsp;&bull;&nbsp; Confidential &nbsp;&bull;&nbsp; &copy; 2026 Aria Intelligence Systems</div>

</div>
</body></html>`,

// ══════════════════════════════════════════════════════════════════════
// t4 — Demand Forecast Weekly Digest
// ══════════════════════════════════════════════════════════════════════
t4: `<!DOCTYPE html><html><head><style>${SHARED_CSS}</style></head><body>
<div class="report-container">

<div class="header">
  <div class="header-logo">
    <svg viewBox="0 0 28 28" fill="none"><rect width="28" height="28" rx="8" fill="#7C3AED"/><path d="M7 14h4l3-6 4 12 3-6h4" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
    <span style="font-size:16px;font-weight:700;">HarmonIQ</span>
  </div>
  <h1>13-Week Demand Forecast Digest &mdash; Week Starting Feb 9, 2026</h1>
  <div class="subtitle">Generated by HarmonIQ &nbsp;|&nbsp; IngestIQ + DemandIQ + VisionIQ</div>
  <div class="date-badge">Forecast Horizon: Feb 9 &ndash; May 10, 2026 &nbsp;&bull;&nbsp; Generated: Feb 9, 2026 06:22 AM</div>
</div>

<div class="exec-summary">
  <h2>Executive Summary</h2>
  <p>The 13-week aggregate demand projection stands at <strong>392K units</strong> (P50), up 3.8% from the prior rolling forecast. Model accuracy has improved with MAPE declining to <strong>6.4%</strong> (&ndash;1.2pp), driven by the incorporation of promotional calendar signals. <strong>14 SKUs (2.9%)</strong> have been flagged as high-risk due to forecast uncertainty exceeding 20%. The ensemble model confidence interval at P80 covers 94.1% of historical actuals.</p>
</div>

<div class="kpi-row">
  <div class="kpi-card"><div class="kpi-label">Projected Demand</div><div class="kpi-value">392K</div><div class="kpi-delta positive">&uarr; +3.8% vs prior</div></div>
  <div class="kpi-card"><div class="kpi-label">MAPE</div><div class="kpi-value">6.4%</div><div class="kpi-delta positive">&darr; -1.2pp improved</div></div>
  <div class="kpi-card"><div class="kpi-label">High-Risk SKUs</div><div class="kpi-value">14</div><div class="kpi-delta negative">2.9% of portfolio</div></div>
  <div class="kpi-card"><div class="kpi-label">Confidence</div><div class="kpi-value">94.1%</div><div class="kpi-delta positive">P80 coverage</div></div>
</div>

<div class="chart-section">
  <h3>Aggregate Demand Forecast (4-Week History + 13-Week Projection)</h3>
  <svg viewBox="0 0 620 280" width="100%" style="display:block;">
    <line x1="50" y1="20" x2="50" y2="220" stroke="#E8E6F0" stroke-width="1"/>
    <line x1="50" y1="220" x2="600" y2="220" stroke="#E8E6F0" stroke-width="1"/>
    <line x1="50" y1="170" x2="600" y2="170" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <line x1="50" y1="120" x2="600" y2="120" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <line x1="50" y1="70" x2="600" y2="70" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <text x="45" y="224" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">20K</text>
    <text x="45" y="174" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">25K</text>
    <text x="45" y="124" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">30K</text>
    <text x="45" y="74" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">35K</text>
    <!-- Divider line: forecast start -->
    <line x1="170" y1="20" x2="170" y2="220" stroke="#7C3AED" stroke-width="1" stroke-dasharray="6,3" opacity="0.5"/>
    <text x="174" y="35" font-size="9" fill="#7C3AED" font-family="DM Sans" font-weight="600">Forecast Start</text>
    <!-- P90 band (top) -->
    <polygon points="170,115 202,108 234,95 266,88 298,80 330,72 362,65 394,58 426,55 458,60 490,65 522,62 554,58 586,52 586,140 554,148 522,155 490,158 458,152 426,148 394,150 362,155 330,160 298,165 266,168 234,172 202,175 170,170" fill="#7C3AED" opacity="0.08"/>
    <!-- P10-P50 lighter band -->
    <polygon points="170,140 202,135 234,128 266,122 298,118 330,112 362,105 394,100 426,97 458,102 490,107 522,104 554,100 586,94 586,140 554,148 522,155 490,158 458,152 426,148 394,150 362,155 330,160 298,165 266,168 234,172 202,175 170,170" fill="#7C3AED" opacity="0.08"/>
    <!-- Historical actual line -->
    <polyline points="74,155 106,148 138,140 170,140" fill="none" stroke="#1A1A2E" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
    <!-- P50 forecast line -->
    <polyline points="170,140 202,135 234,128 266,122 298,118 330,112 362,105 394,100 426,97 458,102 490,107 522,104 554,100 586,94" fill="none" stroke="#7C3AED" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
    <!-- Data points -->
    <circle cx="74" cy="155" r="4" fill="#1A1A2E"/><circle cx="106" cy="148" r="4" fill="#1A1A2E"/>
    <circle cx="138" cy="140" r="4" fill="#1A1A2E"/><circle cx="170" cy="140" r="4" fill="#7C3AED"/>
    <circle cx="298" cy="118" r="4" fill="#7C3AED"/><circle cx="426" cy="97" r="4" fill="#7C3AED"/>
    <circle cx="586" cy="94" r="4" fill="#7C3AED"/>
    <!-- X labels -->
    <text x="74" y="240" text-anchor="middle" font-size="9" fill="#999" font-family="DM Sans">W-3</text>
    <text x="138" y="240" text-anchor="middle" font-size="9" fill="#999" font-family="DM Sans">W-1</text>
    <text x="170" y="240" text-anchor="middle" font-size="9" fill="#999" font-family="DM Sans">W1</text>
    <text x="298" y="240" text-anchor="middle" font-size="9" fill="#999" font-family="DM Sans">W5</text>
    <text x="426" y="240" text-anchor="middle" font-size="9" fill="#999" font-family="DM Sans">W9</text>
    <text x="586" y="240" text-anchor="middle" font-size="9" fill="#999" font-family="DM Sans">W13</text>
    <!-- Legend -->
    <line x1="80" y1="262" x2="100" y2="262" stroke="#1A1A2E" stroke-width="2"/><text x="105" y="266" font-size="10" fill="#666" font-family="DM Sans">Actual</text>
    <line x1="170" y1="262" x2="190" y2="262" stroke="#7C3AED" stroke-width="2"/><text x="195" y="266" font-size="10" fill="#666" font-family="DM Sans">P50 Forecast</text>
    <rect x="290" y="258" width="20" height="8" rx="2" fill="#7C3AED" opacity="0.15"/><text x="315" y="266" font-size="10" fill="#666" font-family="DM Sans">P10&ndash;P90 Band</text>
  </svg>
</div>

<div class="chart-section">
  <h3>Forecast MAPE by Category (%)</h3>
  <svg viewBox="0 0 600 240" width="100%" style="display:block;">
    <line x1="60" y1="20" x2="60" y2="190" stroke="#E8E6F0" stroke-width="1"/>
    <line x1="60" y1="190" x2="580" y2="190" stroke="#E8E6F0" stroke-width="1"/>
    <line x1="60" y1="140" x2="580" y2="140" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <line x1="60" y1="90" x2="580" y2="90" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <line x1="60" y1="40" x2="580" y2="40" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <text x="55" y="194" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">0%</text>
    <text x="55" y="144" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">5%</text>
    <text x="55" y="94" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">10%</text>
    <text x="55" y="44" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">15%</text>
    <!-- Benchmark line at 8% -->
    <line x1="60" y1="114" x2="580" y2="114" stroke="#E74C3C" stroke-width="1" stroke-dasharray="4"/>
    <text x="585" y="118" font-size="9" fill="#E74C3C" font-family="DM Sans">8% Target</text>
    <rect x="85" y="135" width="65" height="55" rx="3" fill="#00B894"/>
    <text x="117" y="130" text-anchor="middle" font-size="11" font-weight="700" fill="#00B894" font-family="DM Sans">5.2%</text>
    <text x="117" y="210" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">Spirits</text>
    <rect x="170" y="128" width="65" height="62" rx="3" fill="#00B894"/>
    <text x="202" y="123" text-anchor="middle" font-size="11" font-weight="700" fill="#00B894" font-family="DM Sans">5.8%</text>
    <text x="202" y="210" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">Beer</text>
    <rect x="255" y="120" width="65" height="70" rx="3" fill="#7C3AED"/>
    <text x="287" y="115" text-anchor="middle" font-size="11" font-weight="700" fill="#7C3AED" font-family="DM Sans">6.4%</text>
    <text x="287" y="210" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">RTD</text>
    <rect x="340" y="108" width="65" height="82" rx="3" fill="#7C3AED"/>
    <text x="372" y="103" text-anchor="middle" font-size="11" font-weight="700" fill="#7C3AED" font-family="DM Sans">7.6%</text>
    <text x="372" y="210" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">Wine</text>
    <rect x="425" y="88" width="65" height="102" rx="3" fill="#E17055"/>
    <text x="457" y="83" text-anchor="middle" font-size="11" font-weight="700" fill="#E17055" font-family="DM Sans">9.4%</text>
    <text x="457" y="210" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">Liqueur</text>
    <rect x="510" y="60" width="65" height="130" rx="3" fill="#E74C3C"/>
    <text x="542" y="55" text-anchor="middle" font-size="11" font-weight="700" fill="#E74C3C" font-family="DM Sans">12.1%</text>
    <text x="542" y="210" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">Seasonal</text>
  </svg>
</div>

<div class="table-section">
  <h3>SKU-Level Forecast Summary &mdash; Top 10</h3>
  <div style="overflow-x:auto;">
  <table class="data-table">
    <thead><tr><th>SKU</th><th>Product</th><th>Wk1</th><th>Wk4</th><th>Wk8</th><th>Wk13</th><th>MAPE</th><th>Risk</th></tr></thead>
    <tbody>
      <tr><td>DG-1042</td><td>JW Black Label 70cl</td><td>8,420</td><td>8,180</td><td>8,650</td><td>9,100</td><td>4.8%</td><td><span class="tag tag-low">Low</span></td></tr>
      <tr><td>DG-3511</td><td>Smirnoff Ice 4pk</td><td>12,100</td><td>11,800</td><td>13,200</td><td>14,500</td><td>5.2%</td><td><span class="tag tag-low">Low</span></td></tr>
      <tr><td>DG-2087</td><td>Tanqueray 70cl</td><td>5,800</td><td>5,600</td><td>6,200</td><td>6,800</td><td>6.1%</td><td><span class="tag tag-low">Low</span></td></tr>
      <tr><td>DG-4420</td><td>Guinness Draught 4pk</td><td>14,200</td><td>13,800</td><td>15,100</td><td>16,400</td><td>5.6%</td><td><span class="tag tag-low">Low</span></td></tr>
      <tr><td>DG-2201</td><td>Gordon&rsquo;s Pink Gin 70cl</td><td>4,200</td><td>4,600</td><td>5,800</td><td>6,100</td><td>8.4%</td><td><span class="tag tag-medium">Medium</span></td></tr>
      <tr><td>DG-6612</td><td>Baileys Original 70cl</td><td>3,100</td><td>2,800</td><td>2,400</td><td>2,100</td><td>11.2%</td><td><span class="tag tag-high">High</span></td></tr>
      <tr><td>DG-1198</td><td>Bulleit Bourbon 70cl</td><td>3,400</td><td>3,200</td><td>3,600</td><td>3,800</td><td>7.2%</td><td><span class="tag tag-low">Low</span></td></tr>
      <tr><td>DG-3088</td><td>Captain Morgan 1L</td><td>4,800</td><td>4,500</td><td>4,200</td><td>3,900</td><td>9.8%</td><td><span class="tag tag-medium">Medium</span></td></tr>
      <tr><td>DG-5530</td><td>Hop House 13 12pk</td><td>3,600</td><td>3,400</td><td>4,100</td><td>4,800</td><td>14.2%</td><td><span class="tag tag-high">High</span></td></tr>
      <tr><td>DG-9920</td><td>Pimm&rsquo;s No.1 70cl</td><td>1,200</td><td>2,800</td><td>5,400</td><td>7,200</td><td>18.6%</td><td><span class="tag tag-high">High</span></td></tr>
    </tbody>
  </table>
  </div>
</div>

<div class="recommendations">
  <h3>Recommendations</h3>
  <ul>
    <li>Pre-position inventory for Pimm&rsquo;s No.1 and Hop House 13, which show steep seasonal ramp-ups starting Week 6; current depot stock covers only 4.2 weeks of projected demand.</li>
    <li>Reduce safety stock on Baileys by 15% as the post-holiday demand decline trajectory is well-characterised (MAPE 11.2% but consistent downward trend).</li>
    <li>Investigate the high MAPE on Seasonal category (12.1%); DemandIQ recommends incorporating weather-adjusted features for improved accuracy.</li>
    <li>Share the P90 scenario with logistics partners by Thursday to secure incremental delivery slots for Weeks 8&ndash;13 peak period.</li>
  </ul>
</div>

<div class="footer">HarmonIQ &mdash; Intelligent Analytics Platform &nbsp;&bull;&nbsp; Confidential &nbsp;&bull;&nbsp; &copy; 2026 Aria Intelligence Systems</div>

</div>
</body></html>`,

// ══════════════════════════════════════════════════════════════════════
// t5 — Shelf Image Compliance Audit
// ══════════════════════════════════════════════════════════════════════
t5: `<!DOCTYPE html><html><head><style>${SHARED_CSS}</style></head><body>
<div class="report-container">

<div class="header">
  <div class="header-logo">
    <svg viewBox="0 0 28 28" fill="none"><rect width="28" height="28" rx="8" fill="#7C3AED"/><path d="M7 14h4l3-6 4 12 3-6h4" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
    <span style="font-size:16px;font-weight:700;">HarmonIQ</span>
  </div>
  <h1>Shelf Compliance Audit Report &mdash; February 2026</h1>
  <div class="subtitle">Generated by HarmonIQ &nbsp;|&nbsp; IngestIQ + VisionIQ+ + MarketIQ</div>
  <div class="date-badge">Audit Period: Feb 1 &ndash; Feb 8, 2026 &nbsp;&bull;&nbsp; Generated: Feb 9, 2026 11:40 AM</div>
</div>

<div class="exec-summary">
  <h2>Executive Summary</h2>
  <p>Shelf compliance across the monitored estate reached <strong>89.2%</strong>, up 4.2 percentage points from January, reflecting improved planogram adherence following targeted field team interventions. <strong>47 non-compliant facings</strong> were detected across 12 stores, primarily in the South East and Midlands regions. Share of shelf stands at <strong>31.4%</strong>, exceeding the 28% target by 3.4pp. Coverage has expanded to 48 stores (92% of the auditable estate).</p>
</div>

<div class="kpi-row">
  <div class="kpi-card"><div class="kpi-label">Compliance</div><div class="kpi-value">89.2%</div><div class="kpi-delta positive">&uarr; +4.2pp vs Jan</div></div>
  <div class="kpi-card"><div class="kpi-label">Non-Compliant</div><div class="kpi-value">47</div><div class="kpi-delta negative">Across 12 stores</div></div>
  <div class="kpi-card"><div class="kpi-label">Share of Shelf</div><div class="kpi-value">31.4%</div><div class="kpi-delta positive">vs 28% target</div></div>
  <div class="kpi-card"><div class="kpi-label">Coverage</div><div class="kpi-value">48 stores</div><div class="kpi-delta positive">92% of estate</div></div>
</div>

<div class="chart-section">
  <h3>Compliance Score by Region (%)</h3>
  <svg viewBox="0 0 600 220" width="100%" style="display:block;">
    <text x="110" y="35" text-anchor="end" font-size="12" fill="#333" font-family="DM Sans" font-weight="500">London</text>
    <rect x="120" y="22" width="380" height="24" rx="4" fill="#7C3AED"/>
    <text x="508" y="39" font-size="12" fill="#7C3AED" font-family="DM Sans" font-weight="700">92.1%</text>
    <text x="110" y="75" text-anchor="end" font-size="12" fill="#333" font-family="DM Sans" font-weight="500">South East</text>
    <rect x="120" y="62" width="373" height="24" rx="4" fill="#7C3AED"/>
    <text x="501" y="79" font-size="12" fill="#7C3AED" font-family="DM Sans" font-weight="700">90.4%</text>
    <text x="110" y="115" text-anchor="end" font-size="12" fill="#333" font-family="DM Sans" font-weight="500">North West</text>
    <rect x="120" y="102" width="364" height="24" rx="4" fill="#A29BFE"/>
    <text x="492" y="119" font-size="12" fill="#A29BFE" font-family="DM Sans" font-weight="700">88.2%</text>
    <text x="110" y="155" text-anchor="end" font-size="12" fill="#333" font-family="DM Sans" font-weight="500">East</text>
    <rect x="120" y="142" width="360" height="24" rx="4" fill="#A29BFE"/>
    <text x="488" y="159" font-size="12" fill="#A29BFE" font-family="DM Sans" font-weight="700">87.1%</text>
    <text x="110" y="195" text-anchor="end" font-size="12" fill="#333" font-family="DM Sans" font-weight="500">Midlands</text>
    <rect x="120" y="182" width="350" height="24" rx="4" fill="#E17055"/>
    <text x="478" y="199" font-size="12" fill="#E17055" font-family="DM Sans" font-weight="700">84.7%</text>
    <!-- 90% benchmark -->
    <line x1="492" y1="15" x2="492" y2="210" stroke="#00B894" stroke-width="1.5" stroke-dasharray="5,3"/>
    <text x="492" y="215" text-anchor="middle" font-size="9" fill="#00B894" font-family="DM Sans" font-weight="600">90% Target</text>
  </svg>
</div>

<div class="chart-section">
  <h3>Share of Shelf Breakdown</h3>
  <svg viewBox="0 0 600 260" width="100%" style="display:block;">
    <!-- Donut chart approximation using arcs -->
    <circle cx="200" cy="130" r="90" fill="none" stroke="#E8E6F0" stroke-width="36"/>
    <!-- Our Brand: 31.4% = 113 degrees -->
    <circle cx="200" cy="130" r="90" fill="none" stroke="#7C3AED" stroke-width="36" stroke-dasharray="178 387" stroke-dashoffset="0" transform="rotate(-90 200 130)"/>
    <!-- Competitor A: 24.2% = 87 degrees -->
    <circle cx="200" cy="130" r="90" fill="none" stroke="#A29BFE" stroke-width="36" stroke-dasharray="137 428" stroke-dashoffset="-178" transform="rotate(-90 200 130)"/>
    <!-- Competitor B: 18.6% = 67 degrees -->
    <circle cx="200" cy="130" r="90" fill="none" stroke="#00B894" stroke-width="36" stroke-dasharray="105 460" stroke-dashoffset="-315" transform="rotate(-90 200 130)"/>
    <!-- Others: 25.8% = 93 degrees (remaining) -->
    <circle cx="200" cy="130" r="90" fill="none" stroke="#E8E6F0" stroke-width="36" stroke-dasharray="146 419" stroke-dashoffset="-420" transform="rotate(-90 200 130)"/>
    <!-- Center text -->
    <text x="200" y="125" text-anchor="middle" font-size="22" font-weight="800" fill="#1A1A2E" font-family="DM Sans">31.4%</text>
    <text x="200" y="145" text-anchor="middle" font-size="11" fill="#999" font-family="DM Sans">Our Share</text>
    <!-- Legend -->
    <rect x="370" y="60" width="14" height="14" rx="3" fill="#7C3AED"/><text x="390" y="72" font-size="13" fill="#333" font-family="DM Sans">Our Brand &mdash; 31.4%</text>
    <rect x="370" y="90" width="14" height="14" rx="3" fill="#A29BFE"/><text x="390" y="102" font-size="13" fill="#333" font-family="DM Sans">Competitor A &mdash; 24.2%</text>
    <rect x="370" y="120" width="14" height="14" rx="3" fill="#00B894"/><text x="390" y="132" font-size="13" fill="#333" font-family="DM Sans">Competitor B &mdash; 18.6%</text>
    <rect x="370" y="150" width="14" height="14" rx="3" fill="#E8E6F0"/><text x="390" y="162" font-size="13" fill="#333" font-family="DM Sans">Others &mdash; 25.8%</text>
  </svg>
</div>

<div class="table-section">
  <h3>Store-Level Compliance Detail</h3>
  <div style="overflow-x:auto;">
  <table class="data-table">
    <thead><tr><th>Store</th><th>Region</th><th>Compliance %</th><th>Facings</th><th>Non-Compliant</th><th>Share of Shelf</th><th>Sell-Through Idx</th></tr></thead>
    <tbody>
      <tr><td>Tesco Metro Covent Garden</td><td>London</td><td>96.4%</td><td>28</td><td>1</td><td>34.2%</td><td>1.18</td></tr>
      <tr><td>Sainsbury&rsquo;s Local Islington</td><td>London</td><td>94.1%</td><td>24</td><td>2</td><td>32.8%</td><td>1.12</td></tr>
      <tr><td>Tesco Express Brighton</td><td>South East</td><td>92.8%</td><td>22</td><td>2</td><td>30.6%</td><td>1.08</td></tr>
      <tr><td>Morrisons Manchester</td><td>North West</td><td>90.2%</td><td>30</td><td>3</td><td>31.0%</td><td>1.04</td></tr>
      <tr><td>Asda Norwich</td><td>East</td><td>88.6%</td><td>26</td><td>3</td><td>29.4%</td><td>0.98</td></tr>
      <tr><td>Co-op Liverpool</td><td>North West</td><td>87.4%</td><td>20</td><td>4</td><td>30.2%</td><td>1.01</td></tr>
      <tr><td>Waitrose Guildford</td><td>South East</td><td>86.2%</td><td>32</td><td>5</td><td>33.6%</td><td>1.15</td></tr>
      <tr><td>Tesco Extra Birmingham</td><td>Midlands</td><td>84.0%</td><td>34</td><td>6</td><td>28.4%</td><td>0.94</td></tr>
      <tr><td>Sainsbury&rsquo;s Nottingham</td><td>Midlands</td><td>82.1%</td><td>28</td><td>5</td><td>27.8%</td><td>0.91</td></tr>
      <tr><td>Asda Coventry</td><td>Midlands</td><td>78.6%</td><td>22</td><td>8</td><td>26.2%</td><td>0.86</td></tr>
    </tbody>
  </table>
  </div>
</div>

<div class="recommendations">
  <h3>Recommendations</h3>
  <ul>
    <li>Prioritise field team visits to the 3 Midlands stores (Birmingham, Nottingham, Coventry) where compliance is below 85% and sell-through index is under 0.95.</li>
    <li>Investigate the 8 non-compliant facings at Asda Coventry; VisionIQ+ detected competitor product encroachment in 5 of 8 cases, suggesting deliberate planogram deviation.</li>
    <li>Replicate the London playbook (96.4% avg compliance) across South East stores by sharing best-practice imagery and positioning guides with regional merchandising teams.</li>
    <li>Expand the audit programme to the remaining 4 non-covered stores (8% gap) to achieve full estate visibility by March 2026.</li>
  </ul>
</div>

<div class="footer">HarmonIQ &mdash; Intelligent Analytics Platform &nbsp;&bull;&nbsp; Confidential &nbsp;&bull;&nbsp; &copy; 2026 Aria Intelligence Systems</div>

</div>
</body></html>`,

// ══════════════════════════════════════════════════════════════════════
// t6 — Promotional ROI Analyzer
// ══════════════════════════════════════════════════════════════════════
t6: `<!DOCTYPE html><html><head><style>${SHARED_CSS}</style></head><body>
<div class="report-container">

<div class="header">
  <div class="header-logo">
    <svg viewBox="0 0 28 28" fill="none"><rect width="28" height="28" rx="8" fill="#7C3AED"/><path d="M7 14h4l3-6 4 12 3-6h4" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
    <span style="font-size:16px;font-weight:700;">HarmonIQ</span>
  </div>
  <h1>Promotional ROI Analysis &mdash; H2 2025</h1>
  <div class="subtitle">Generated by HarmonIQ &nbsp;|&nbsp; IngestIQ + MarketIQ + DemandIQ + OptimaIQ + VisionIQ</div>
  <div class="date-badge">Analysis Period: Jul 1 &ndash; Dec 31, 2025 &nbsp;&bull;&nbsp; Generated: Feb 8, 2026 09:15 AM</div>
</div>

<div class="exec-summary">
  <h2>Executive Summary</h2>
  <p>The H2 2025 promotional portfolio delivered a blended <strong>ROI of 2.1:1</strong>, up 0.3 points from the trailing average, with <strong>116K net incremental units</strong> after adjusting for pull-forward and cannibalisation effects. Display-led mechanics outperformed all other formats at <strong>3.1:1 ROI</strong> (+48% vs average), while BOGOF campaigns underperformed at 1.4:1. OptimaIQ identifies a <strong>&pound;420K savings opportunity</strong> by reallocating 18% of trade spend from underperforming mechanics to high-ROI formats.</p>
</div>

<div class="kpi-row">
  <div class="kpi-card"><div class="kpi-label">Portfolio ROI</div><div class="kpi-value">2.1 : 1</div><div class="kpi-delta positive">&uarr; +0.3 vs avg</div></div>
  <div class="kpi-card"><div class="kpi-label">Net Incremental</div><div class="kpi-value">116K</div><div class="kpi-delta positive">Adj. for pull-forward</div></div>
  <div class="kpi-card"><div class="kpi-label">Best Mechanic</div><div class="kpi-value">Display 3.1:1</div><div class="kpi-delta positive">&uarr; +48% vs avg</div></div>
  <div class="kpi-card"><div class="kpi-label">Savings Opportunity</div><div class="kpi-value">&pound;420K</div><div class="kpi-delta positive">&uarr; +18% ROI uplift</div></div>
</div>

<div class="chart-section">
  <h3>ROI by Promotion Mechanic</h3>
  <svg viewBox="0 0 600 280" width="100%" style="display:block;">
    <line x1="60" y1="20" x2="60" y2="230" stroke="#E8E6F0" stroke-width="1"/>
    <line x1="60" y1="230" x2="560" y2="230" stroke="#E8E6F0" stroke-width="1"/>
    <line x1="60" y1="180" x2="560" y2="180" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <line x1="60" y1="130" x2="560" y2="130" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <line x1="60" y1="80" x2="560" y2="80" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <line x1="60" y1="30" x2="560" y2="30" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <text x="55" y="234" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">0.0</text>
    <text x="55" y="184" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">1.0</text>
    <text x="55" y="134" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">2.0</text>
    <text x="55" y="84" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">3.0</text>
    <text x="55" y="34" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">4.0</text>
    <!-- Benchmark line at 1.8 -->
    <line x1="60" y1="140" x2="560" y2="140" stroke="#E17055" stroke-width="1.5" stroke-dasharray="6,3"/>
    <text x="564" y="144" font-size="9" fill="#E17055" font-family="DM Sans" font-weight="600">1.8 Benchmark</text>
    <!-- Display bar: 3.1 -->
    <rect x="100" y="75" width="80" height="155" rx="3" fill="#00B894"/>
    <text x="140" y="68" text-anchor="middle" font-size="13" font-weight="700" fill="#00B894" font-family="DM Sans">3.1</text>
    <text x="140" y="250" text-anchor="middle" font-size="11" fill="#666" font-family="DM Sans">Display</text>
    <!-- Price Cut bar: 2.6 -->
    <rect x="220" y="100" width="80" height="130" rx="3" fill="#7C3AED"/>
    <text x="260" y="93" text-anchor="middle" font-size="13" font-weight="700" fill="#7C3AED" font-family="DM Sans">2.6</text>
    <text x="260" y="250" text-anchor="middle" font-size="11" fill="#666" font-family="DM Sans">Price Cut</text>
    <!-- Multibuy bar: 2.2 -->
    <rect x="340" y="120" width="80" height="110" rx="3" fill="#A29BFE"/>
    <text x="380" y="113" text-anchor="middle" font-size="13" font-weight="700" fill="#A29BFE" font-family="DM Sans">2.2</text>
    <text x="380" y="250" text-anchor="middle" font-size="11" fill="#666" font-family="DM Sans">Multibuy</text>
    <!-- BOGOF bar: 1.4 -->
    <rect x="460" y="160" width="80" height="70" rx="3" fill="#E74C3C"/>
    <text x="500" y="153" text-anchor="middle" font-size="13" font-weight="700" fill="#E74C3C" font-family="DM Sans">1.4</text>
    <text x="500" y="250" text-anchor="middle" font-size="11" fill="#666" font-family="DM Sans">BOGOF</text>
  </svg>
</div>

<div class="chart-section">
  <h3>Monthly Incremental Lift (Jul &ndash; Dec 2025, 000s Units)</h3>
  <svg viewBox="0 0 600 250" width="100%" style="display:block;">
    <line x1="50" y1="20" x2="50" y2="200" stroke="#E8E6F0" stroke-width="1"/>
    <line x1="50" y1="200" x2="570" y2="200" stroke="#E8E6F0" stroke-width="1"/>
    <line x1="50" y1="155" x2="570" y2="155" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <line x1="50" y1="110" x2="570" y2="110" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <line x1="50" y1="65" x2="570" y2="65" stroke="#E8E6F0" stroke-width="0.5" stroke-dasharray="4"/>
    <text x="45" y="204" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">0</text>
    <text x="45" y="159" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">10K</text>
    <text x="45" y="114" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">20K</text>
    <text x="45" y="69" text-anchor="end" font-size="10" fill="#999" font-family="DM Sans">30K</text>
    <!-- Line: Jul 14K, Aug 16K, Sep 18K, Oct 22K, Nov 28K, Dec 18K -->
    <polyline points="90,137 180,128 270,119 360,101 450,74 540,119" fill="none" stroke="#7C3AED" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
    <!-- Area fill -->
    <polygon points="90,137 180,128 270,119 360,101 450,74 540,119 540,200 90,200" fill="#7C3AED" opacity="0.08"/>
    <!-- Data points -->
    <circle cx="90" cy="137" r="5" fill="#7C3AED"/><text x="90" y="130" text-anchor="middle" font-size="10" font-weight="700" fill="#7C3AED" font-family="DM Sans">14K</text>
    <circle cx="180" cy="128" r="5" fill="#7C3AED"/><text x="180" y="121" text-anchor="middle" font-size="10" font-weight="700" fill="#7C3AED" font-family="DM Sans">16K</text>
    <circle cx="270" cy="119" r="5" fill="#7C3AED"/><text x="270" y="112" text-anchor="middle" font-size="10" font-weight="700" fill="#7C3AED" font-family="DM Sans">18K</text>
    <circle cx="360" cy="101" r="5" fill="#7C3AED"/><text x="360" y="94" text-anchor="middle" font-size="10" font-weight="700" fill="#7C3AED" font-family="DM Sans">22K</text>
    <circle cx="450" cy="74" r="5" fill="#00B894"/><text x="450" y="67" text-anchor="middle" font-size="10" font-weight="700" fill="#00B894" font-family="DM Sans">28K</text>
    <circle cx="540" cy="119" r="5" fill="#7C3AED"/><text x="540" y="112" text-anchor="middle" font-size="10" font-weight="700" fill="#7C3AED" font-family="DM Sans">18K</text>
    <!-- X labels -->
    <text x="90" y="218" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">Jul</text>
    <text x="180" y="218" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">Aug</text>
    <text x="270" y="218" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">Sep</text>
    <text x="360" y="218" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">Oct</text>
    <text x="450" y="218" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">Nov</text>
    <text x="540" y="218" text-anchor="middle" font-size="10" fill="#666" font-family="DM Sans">Dec</text>
  </svg>
</div>

<div class="table-section">
  <h3>Campaign-Level Performance Detail</h3>
  <div style="overflow-x:auto;">
  <table class="data-table">
    <thead><tr><th>Campaign</th><th>Brand</th><th>Mechanic</th><th>Spend (&pound;)</th><th>Gross Lift</th><th>Net Lift</th><th>ROI</th><th>Recommendation</th></tr></thead>
    <tbody>
      <tr><td>Summer Spirits Splash</td><td>Tanqueray</td><td>Display</td><td>&pound;82,000</td><td>18,400</td><td>14,200</td><td>3.4:1</td><td><span class="tag tag-low">Scale Up</span></td></tr>
      <tr><td>BBQ Season Bundle</td><td>Smirnoff</td><td>Multibuy</td><td>&pound;64,000</td><td>14,800</td><td>10,600</td><td>2.4:1</td><td><span class="tag tag-low">Maintain</span></td></tr>
      <tr><td>Whisky Weekend</td><td>J. Walker</td><td>Price Cut</td><td>&pound;95,000</td><td>22,200</td><td>18,400</td><td>2.8:1</td><td><span class="tag tag-low">Scale Up</span></td></tr>
      <tr><td>Freshers Week</td><td>Smirnoff</td><td>BOGOF</td><td>&pound;48,000</td><td>12,600</td><td>5,800</td><td>1.2:1</td><td><span class="tag tag-high">Redesign</span></td></tr>
      <tr><td>October Fest</td><td>Guinness</td><td>Display</td><td>&pound;72,000</td><td>20,100</td><td>16,800</td><td>3.2:1</td><td><span class="tag tag-low">Scale Up</span></td></tr>
      <tr><td>Dark Spirits Promo</td><td>Bulleit</td><td>Price Cut</td><td>&pound;38,000</td><td>8,200</td><td>6,400</td><td>2.6:1</td><td><span class="tag tag-low">Maintain</span></td></tr>
      <tr><td>Black Friday Deals</td><td>Multi-brand</td><td>Multibuy</td><td>&pound;110,000</td><td>32,400</td><td>22,600</td><td>2.1:1</td><td><span class="tag tag-medium">Optimise</span></td></tr>
      <tr><td>Xmas Gift Sets</td><td>J. Walker</td><td>Display</td><td>&pound;88,000</td><td>24,600</td><td>19,200</td><td>2.9:1</td><td><span class="tag tag-low">Maintain</span></td></tr>
      <tr><td>New Year Bundle</td><td>Multi-brand</td><td>BOGOF</td><td>&pound;56,000</td><td>10,800</td><td>4,200</td><td>1.1:1</td><td><span class="tag tag-high">Discontinue</span></td></tr>
      <tr><td>Winter Warmers</td><td>Baileys</td><td>Price Cut</td><td>&pound;34,000</td><td>7,600</td><td>5,800</td><td>2.2:1</td><td><span class="tag tag-low">Maintain</span></td></tr>
    </tbody>
  </table>
  </div>
</div>

<div class="recommendations">
  <h3>Recommendations</h3>
  <ul>
    <li>Reallocate &pound;104K from BOGOF mechanics (Freshers Week, New Year Bundle) to Display-led campaigns, which deliver 2.2x higher net ROI on average.</li>
    <li>Scale the &ldquo;Summer Spirits Splash&rdquo; Display format to 3 additional brands in H1 2026; the 3.4:1 ROI template is replicable across Spirits portfolio per OptimaIQ scenario modelling.</li>
    <li>Redesign the Black Friday Multibuy structure to reduce cannibalisation; DemandIQ estimates 28% of gross lift was pull-forward from adjacent weeks.</li>
    <li>Establish a minimum ROI threshold of 1.8:1 for all future promotional approvals, which would have flagged 2 of 10 H2 campaigns for redesign before execution.</li>
  </ul>
</div>

<div class="footer">HarmonIQ &mdash; Intelligent Analytics Platform &nbsp;&bull;&nbsp; Confidential &nbsp;&bull;&nbsp; &copy; 2026 Aria Intelligence Systems</div>

</div>
</body></html>`,

// ══════════════════════════════════════════════════════════════════════
// t7 — Pharma Content Compliance Audit
// ══════════════════════════════════════════════════════════════════════
t7: `<!DOCTYPE html><html><head><style>${SHARED_CSS}
.compliance-bar{height:22px;border-radius:6px;position:relative;overflow:hidden;background:#EDEBF5;}
.compliance-fill{height:100%;border-radius:6px;transition:width 0.5s;}
.compliance-label{position:absolute;right:8px;top:2px;font-size:11px;font-weight:700;color:#fff;}
.severity-badge{display:inline-block;padding:3px 10px;border-radius:6px;font-size:11px;font-weight:700;}
.sev-critical{background:#FFEAEA;color:#E74C3C;}
.sev-major{background:#FFF4E0;color:#E17055;}
.sev-minor{background:#E8FFF0;color:#00B894;}
.status-supported{background:#E8FFF0;color:#00B894;padding:2px 8px;border-radius:6px;font-size:11px;font-weight:600;}
.status-unsupported{background:#FFEAEA;color:#E74C3C;padding:2px 8px;border-radius:6px;font-size:11px;font-weight:600;}
.status-partial{background:#FFF4E0;color:#E17055;padding:2px 8px;border-radius:6px;font-size:11px;font-weight:600;}
.pharma-header{background:linear-gradient(135deg,#1A1A2E 0%,#0D4F4F 60%,#134E5E 100%);}
</style></head><body>
<div class="report-container">

<div class="header pharma-header">
  <div class="header-logo">
    <svg viewBox="0 0 28 28" fill="none"><circle cx="14" cy="14" r="13" stroke="#00B894" stroke-width="2"/><path d="M9 14h10M14 9v10" stroke="#00B894" stroke-width="2.5" stroke-linecap="round"/></svg>
    <span style="font-size:13px;font-weight:700;color:#00B894;">NovaCure Pharmaceuticals</span>
  </div>
  <h1>Pharmaceutical Content Compliance Audit</h1>
  <div class="subtitle">NeuroCalm 50mg &mdash; Pre-Launch Content Review &amp; Regulatory Risk Assessment</div>
  <div class="date-badge">Generated: Feb 14, 2026 07:15 AM &nbsp;&bull;&nbsp; Workflow: Pharma Content Compliance Audit &nbsp;&bull;&nbsp; Auditor: HarmonIQ Mother Agent</div>
</div>

<div class="exec-summary">
  <h2>Executive Summary</h2>
  <p>Comprehensive compliance audit of <strong>5 NeuroCalm 50mg content assets</strong> (186 PDF pages, 12,480 clinical data rows, 3,842 adverse event records) identified <strong>6 regulatory issues</strong>: 2 critical (unsupported efficacy claims &amp; off-label language), 3 major (adverse event reporting gaps &amp; ABPI code deviations), and 1 minor (version formatting). The marketing brochure scores <strong>71/100</strong> and requires remediation before launch. SmPC scores a strong <strong>94/100</strong>. Competitive benchmarking reveals NeuroCalm&rsquo;s single-indication profile (GAD only) is the narrowest in class, presenting a label extension opportunity. An optimized <strong>12-business-day remediation plan</strong> preserves the Q2 launch window.</p>
</div>

<div class="kpi-row">
  <div class="kpi-card"><div class="kpi-label">Content Assets Audited</div><div class="kpi-value">5</div><div class="kpi-delta positive">186 pages + 16K rows</div></div>
  <div class="kpi-card"><div class="kpi-label">Avg Compliance Score</div><div class="kpi-value">82/100</div><div class="kpi-delta negative">Brochure 71 drags avg</div></div>
  <div class="kpi-card"><div class="kpi-label">Flagged Issues</div><div class="kpi-value">6</div><div class="kpi-delta negative">2 critical, 3 major, 1 minor</div></div>
  <div class="kpi-card"><div class="kpi-label">Days to Compliance</div><div class="kpi-value">12</div><div class="kpi-delta positive">Optimized from 22 days</div></div>
</div>

<div class="chart-section">
  <h3>Compliance Score by Document</h3>
  <svg viewBox="0 0 700 220" style="width:100%;max-width:700px;">
    <text x="0" y="22" font-size="12" fill="#555" font-weight="600">SmPC v3.2</text>
    <rect x="160" y="8" width="480" height="20" rx="4" fill="#EDEBF5"/><rect x="160" y="8" width="451" height="20" rx="4" fill="#00B894"/><text x="620" y="23" font-size="11" fill="#fff" font-weight="700">94</text>

    <text x="0" y="56" font-size="12" fill="#555" font-weight="600">Clinical Trial Data</text>
    <rect x="160" y="42" width="480" height="20" rx="4" fill="#EDEBF5"/><rect x="160" y="42" width="461" height="20" rx="4" fill="#00B894"/><text x="630" y="57" font-size="11" fill="#fff" font-weight="700">96</text>

    <text x="0" y="90" font-size="12" fill="#555" font-weight="600">AE Reports</text>
    <rect x="160" y="76" width="480" height="20" rx="4" fill="#EDEBF5"/><rect x="160" y="76" width="422" height="20" rx="4" fill="#FDCB6E"/><text x="590" y="91" font-size="11" fill="#333" font-weight="700">88</text>

    <text x="0" y="124" font-size="12" fill="#555" font-weight="600">Patient Info Leaflet</text>
    <rect x="160" y="110" width="480" height="20" rx="4" fill="#EDEBF5"/><rect x="160" y="110" width="403" height="20" rx="4" fill="#FDCB6E"/><text x="571" y="125" font-size="11" fill="#333" font-weight="700">84</text>

    <text x="0" y="158" font-size="12" fill="#555" font-weight="600">Visual Assets</text>
    <rect x="160" y="144" width="480" height="20" rx="4" fill="#EDEBF5"/><rect x="160" y="144" width="374" height="20" rx="4" fill="#E17055"/><text x="542" y="159" font-size="11" fill="#fff" font-weight="700">78</text>

    <text x="0" y="192" font-size="12" fill="#555" font-weight="600">Marketing Brochure</text>
    <rect x="160" y="178" width="480" height="20" rx="4" fill="#EDEBF5"/><rect x="160" y="178" width="341" height="20" rx="4" fill="#E74C3C"/><text x="509" y="193" font-size="11" fill="#fff" font-weight="700">71</text>
  </svg>
</div>

<div class="table-section">
  <h3>Flagged Issues Detail</h3>
  <div style="overflow-x:auto;">
  <table class="data-table">
    <thead><tr><th>Issue ID</th><th>Document</th><th>Severity</th><th>Description</th><th>Regulatory Ref</th><th>Remediation</th></tr></thead>
    <tbody>
      <tr><td>ISS-001</td><td>Marketing Brochure</td><td><span class="severity-badge sev-critical">Critical</span></td><td>Off-label claim: &ldquo;manages anxiety-related insomnia&rdquo; &mdash; insomnia not in approved indications</td><td>ABPI Code &sect;3.2</td><td>Remove claim; replace with approved GAD language</td></tr>
      <tr><td>ISS-002</td><td>Marketing Brochure</td><td><span class="severity-badge sev-critical">Critical</span></td><td>Unsupported superiority claim: &ldquo;superior efficacy vs SSRIs&rdquo; with no head-to-head trial data</td><td>EMA Art. 87(3)</td><td>Remove or add disclaimer: &ldquo;not directly compared in clinical trials&rdquo;</td></tr>
      <tr><td>ISS-003</td><td>Patient Info Leaflet</td><td><span class="severity-badge sev-major">Major</span></td><td>3 SAEs with incidence &gt;0.1% missing from PIL Section 4 (dizziness, elevated liver enzymes, QT prolongation)</td><td>MHRA PV Reg &sect;12</td><td>Add SAEs with frequency categorization (Uncommon)</td></tr>
      <tr><td>ISS-004</td><td>HCP Communication</td><td><span class="severity-badge sev-major">Major</span></td><td>Missing mandatory prescribing information link in HCP email template</td><td>ABPI Code &sect;4.1</td><td>Add SmPC hyperlink to email footer</td></tr>
      <tr><td>ISS-005</td><td>HCP Communication</td><td><span class="severity-badge sev-major">Major</span></td><td>Adverse event summary incomplete &mdash; only lists top 5 of 18 AEs reported in Phase III</td><td>ABPI Code &sect;4.2</td><td>Expand AE summary to include all AEs with &gt;1% incidence</td></tr>
      <tr><td>ISS-006</td><td>Visual Assets</td><td><span class="severity-badge sev-minor">Minor</span></td><td>MoA diagram version tag (v1.0) does not follow NovaCure document versioning standard (NC-VIS-YYYY-NNN)</td><td>Internal SOP-DM-04</td><td>Update version tag to NC-VIS-2026-001</td></tr>
    </tbody>
  </table>
  </div>
</div>

<div class="table-section">
  <h3>Claim-to-Evidence Traceability Matrix</h3>
  <div style="overflow-x:auto;">
  <table class="data-table">
    <thead><tr><th>#</th><th>Marketing Claim</th><th>SmPC Reference</th><th>Clinical Evidence</th><th>Status</th></tr></thead>
    <tbody>
      <tr><td>1</td><td>Reduces HAM-A scores by 52% at Week 8</td><td>&sect;5.1 Primary endpoint</td><td>p&lt;0.001 vs placebo (n=1,240)</td><td><span class="status-supported">Supported</span></td></tr>
      <tr><td>2</td><td>Rapid onset of action within 2 weeks</td><td>&sect;5.1 Secondary endpoint</td><td>Significant at Week 2 (p=0.003)</td><td><span class="status-supported">Supported</span></td></tr>
      <tr><td>3</td><td>Well-tolerated safety profile</td><td>&sect;4.8 Undesirable effects</td><td>Discontinuation 4.2% vs 3.8% placebo</td><td><span class="status-supported">Supported</span></td></tr>
      <tr><td>4</td><td>Once-daily convenient dosing</td><td>&sect;4.2 Posology</td><td>50mg QD, no titration required</td><td><span class="status-supported">Supported</span></td></tr>
      <tr><td>5</td><td>Reduces anxiety-related insomnia by 40%</td><td><em>NOT IN &sect;4.1</em></td><td>Post-hoc analysis only (not pre-specified)</td><td><span class="status-unsupported">Unsupported</span></td></tr>
      <tr><td>6</td><td>Superior efficacy vs. SSRIs</td><td><em>No head-to-head data</em></td><td>Indirect comparison only (network meta-analysis)</td><td><span class="status-unsupported">Unsupported</span></td></tr>
      <tr><td>7</td><td>Sustained remission at 6 months</td><td>&sect;5.1 Long-term extension</td><td>68% remission rate at 24 weeks</td><td><span class="status-supported">Supported</span></td></tr>
      <tr><td>8</td><td>No significant weight gain</td><td>&sect;4.8 Metabolic effects</td><td>Mean +0.3 kg vs +0.2 kg placebo</td><td><span class="status-supported">Supported</span></td></tr>
      <tr><td>9</td><td>Minimal drug-drug interactions</td><td>&sect;4.5 Interactions</td><td>Weak CYP3A4 substrate</td><td><span class="status-supported">Supported</span></td></tr>
      <tr><td>10</td><td>Improved patient quality of life (Q-LES-Q)</td><td>&sect;5.1 QoL endpoint</td><td>p=0.008 vs placebo</td><td><span class="status-supported">Supported</span></td></tr>
      <tr><td>11</td><td>Low potential for dependence</td><td>&sect;4.4 Special warnings</td><td>No evidence of rebound anxiety in 8-week taper</td><td><span class="status-partial">Partial</span></td></tr>
      <tr><td>12</td><td>Suitable for elderly patients</td><td>&sect;4.2 Special populations</td><td>Dose adjustment not required &ge;65 years</td><td><span class="status-supported">Supported</span></td></tr>
      <tr><td>13</td><td>Novel GABA-A modulator mechanism</td><td>&sect;5.1 Pharmacodynamics</td><td>Selective positive allosteric modulator</td><td><span class="status-supported">Supported</span></td></tr>
      <tr><td>14</td><td>Clinically meaningful response from Week 1</td><td>&sect;5.1 Early response</td><td>CGI-I improvement at Day 7 (p=0.04)</td><td><span class="status-partial">Partial</span></td></tr>
    </tbody>
  </table>
  </div>
</div>

<div class="table-section">
  <h3>Remediation Priority Plan</h3>
  <div style="overflow-x:auto;">
  <table class="data-table">
    <thead><tr><th>Priority</th><th>Action</th><th>Risk Score</th><th>Owner</th><th>Deadline</th><th>Status</th></tr></thead>
    <tbody>
      <tr><td><span class="tag tag-high">P1</span></td><td>Remove off-label insomnia claim from marketing brochure (pg 8)</td><td>9.2 / 10</td><td>Medical Affairs</td><td>Feb 17</td><td><span class="tag tag-high">Open</span></td></tr>
      <tr><td><span class="tag tag-high">P2</span></td><td>Add superiority disclaimer or remove SSRI comparison claim</td><td>8.8 / 10</td><td>Medical Affairs</td><td>Feb 18</td><td><span class="tag tag-high">Open</span></td></tr>
      <tr><td><span class="tag tag-medium">P3</span></td><td>Add 3 missing SAEs to Patient Information Leaflet Section 4</td><td>7.4 / 10</td><td>Pharmacovigilance</td><td>Feb 21</td><td><span class="tag tag-medium">Open</span></td></tr>
      <tr><td><span class="tag tag-medium">P4</span></td><td>Add prescribing information link to HCP email template</td><td>6.8 / 10</td><td>Regulatory Affairs</td><td>Feb 19</td><td><span class="tag tag-medium">Open</span></td></tr>
      <tr><td><span class="tag tag-medium">P5</span></td><td>Expand AE summary in HCP communication to include all AEs &gt;1%</td><td>6.2 / 10</td><td>Medical Writing</td><td>Feb 20</td><td><span class="tag tag-medium">Open</span></td></tr>
      <tr><td><span class="tag tag-low">P6</span></td><td>Update MoA diagram version tag to NovaCure standard</td><td>2.1 / 10</td><td>Document Control</td><td>Feb 24</td><td><span class="tag tag-low">Open</span></td></tr>
    </tbody>
  </table>
  </div>
</div>

<div class="table-section">
  <h3>Competitive Regulatory Landscape</h3>
  <div style="overflow-x:auto;">
  <table class="data-table">
    <thead><tr><th>Product</th><th>Company</th><th>Approved Indications</th><th>GAD Market Share</th><th>EMA Warning Letters (24mo)</th><th>Compliance Rating</th></tr></thead>
    <tbody>
      <tr><td><strong>NeuroCalm 50mg</strong></td><td>NovaCure</td><td>1 (GAD)</td><td>New entrant</td><td>0</td><td><span class="tag tag-low">82/100</span></td></tr>
      <tr><td>Serenazen 25mg</td><td>BrandX Pharma</td><td>3 (GAD, SAD, PD)</td><td>28.4%</td><td>0</td><td><span class="tag tag-low">91/100</span></td></tr>
      <tr><td>CalmPro 100mg</td><td>BrandY Labs</td><td>2 (GAD, MDD-adj)</td><td>22.1%</td><td>0</td><td><span class="tag tag-low">88/100</span></td></tr>
      <tr><td>AnxiRelief 75mg</td><td>BrandZ Bio</td><td>2 (GAD, Insomnia)</td><td>18.7%</td><td>1</td><td><span class="tag tag-medium">76/100</span></td></tr>
      <tr><td>TranquiLex 50mg</td><td>BrandW Corp</td><td>4 (GAD, SAD, PD, OCD)</td><td>31.2%</td><td>0</td><td><span class="tag tag-low">93/100</span></td></tr>
    </tbody>
  </table>
  </div>
</div>

<div class="recommendations">
  <h3>Recommendations</h3>
  <ul>
    <li><strong>Immediate (P1-P2):</strong> Remove the off-label insomnia claim and unsupported SSRI superiority statement from the marketing brochure before MLR review. Medical Affairs to provide compliant replacement language within 3 business days.</li>
    <li><strong>Short-term (P3-P5):</strong> Update the Patient Information Leaflet with 3 missing SAEs (dizziness 0.8%, elevated liver enzymes 0.3%, QT prolongation 0.12%) and expand the HCP communication AE summary. Pharmacovigilance to lead, target 7 business days.</li>
    <li><strong>Strategic:</strong> File a label extension application for &ldquo;generalised anxiety disorder with sleep disturbance&rdquo; to match competitor indication breadth. AnxiRelief (BrandZ) already holds insomnia indication &mdash; clinical evidence from NeuroCalm post-hoc analysis could support a Phase IIIb study.</li>
    <li><strong>Process Improvement:</strong> Establish automated claim-to-SmPC traceability checks in the content management system. This audit identified 2 claims that passed 3 rounds of manual MLR review &mdash; automated cross-validation would have flagged them at draft stage, saving an estimated 15 business days per launch cycle.</li>
  </ul>
</div>

<div class="footer">HarmonIQ &mdash; Intelligent Analytics Platform &nbsp;&bull;&nbsp; NovaCure Pharmaceuticals &mdash; Confidential &nbsp;&bull;&nbsp; &copy; 2026 Aria Intelligence Systems</div>

</div>
</body></html>`,

};

export default CANVAS_REPORTS;
